# ===============================
# APP
# ===============================
spring.application.name=smartcampus-admin
server.port=${PORT:8090}
server.servlet.context-path=/api

# ===============================
# MYSQL
# ===============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# ===============================
# JWT
# ===============================
jwt.secret=smartcampus-uis-proyecto-grado-secret-key-2026-muy-larga
jwt.expiration-ms=86400000

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false