# ===============================
# APP
# ===============================
spring.application.name=smartcampus-admin
server.port=${PORT:8090}
server.servlet.context-path=/api

# ===============================
# MYSQL
# ===============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# MAIL (Gmail SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartcampus.uis@gmail.com
spring.mail.password=auereaxteolbletk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================
# JWT
# ===============================
jwt.secret=smartcampus-uis-proyecto-grado-secret-key-2026-muy-larga
jwt.expiration-ms=86400000

# Alertas
alert.mail.recipient=smartcampus.uis@gmail.com
alert.threshold.temperature=80.0
alert.threshold.battery=10.0
alert.cooldown.minutes=30

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false